### ISSUE TITLE
^D starts an endless loop

### ISSUE THREAD

**Issue by kseistrup** [ThakeeNathees/pocketlang#105]
I wanted to exit `pocket` with a `^D` in the terminal. Instead pocket printed out `>>> ` in an endless loop:

```sh
$ pocket
PocketLang 0.1.0 (https://github.com/ThakeeNathees/pocketlang/)
Copyright(c) 2020 - 2021 ThakeeNathees.
Free and open source software under the terms of the MIT license.

>>> ^D
>>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>>^C
$ 
```

This is commit 2b4d3af0a24a3952334c54fcf409e9fd9d27eaf2

```sh
$ uname -omp
x86_64 unknown GNU/Linux
```

**Comment by ThakeeNathees** [comment]
Signals haven't handled in pocketlang yet, However `SIGINT` (ctrl+c) will terminate the process. I'll add this to my TODOs

Thanks for reporting this issue.

**Comment by tsujp** [comment]
I can take a crack at this tonight @ThakeeNathees which signals did you want processed?

**Comment by ThakeeNathees** [comment]
@tsujp For now, I'd only like to handle `SIGINT`, I'm not quite experienced with signals feel free to add more. We don't have error handling yet, so now, this should run the cleanups `pkFreeVM(vm);` (at the end of the main) and terminate the process with a non-zero exit code.

**Comment by tsujp** [comment]
I've sort of drifted into trying to solve both ^D spam (I think I know how it's happening but I cannot yet solve it) and adding the ability to handle signals. Right now ^C works _anyway_ but in the future we might want more signals so it's still valuable I reckon.

I'm having a bit of trouble deciding how I'd do this. Signal handlers cannot have arguments passed to them (they could but it's undefined behaviour) and we need an argument, the `vm` in order to `pkFreeVM(vm)` it.

If there was a main loop which didn't block we could use a single global struct which holds a field "bool executing" and set that field to `false` in the signal handler, thereby ending the loop after which `pkFreeVM(vm)` is reached afterwards. There is no single main loop, and the loops there are are blocking so this approach isn't key either.

There is this do-while for `repl` here https://github.com/ThakeeNathees/pocketlang/blob/master/cli/repl.c#L84 but this blocks while waiting for the line to be completed.

As for non-repl mode there are some checks run and then we compile the source input: https://github.com/ThakeeNathees/pocketlang/blob/64bf27674a068a008a78a545e7e353d5659dd1e9/src/pk_vm.c#L152 (where is compile implemented I cannot see it?) and then we run the compiled source on a fiber: https://github.com/ThakeeNathees/pocketlang/blob/64bf27674a068a008a78a545e7e353d5659dd1e9/src/pk_vm.c#L160 which is this https://github.com/ThakeeNathees/pocketlang/blob/64bf27674a068a008a78a545e7e353d5659dd1e9/src/pk_vm.c#L606

So, perhaps the signal processing should be in the fiber for non-repl and `repl` should have some kind of non-blocking loop to enable signal handling?

My systems programming is woefully average (for now ;) hehe) even before years of non-use so I am a bit stuck now @ThakeeNathees

**Comment by ThakeeNathees** [comment]
> where is compile implemented I cannot see it?

It's declared at [src/pk_compiler.h](https://github.com/ThakeeNathees/pocketlang/blob/6d434db0cb7da2699c45b455f23032dab65b633b/src/pk_compiler.h#L28-L33)
And defined at [src/pk_compiler.c](https://github.com/ThakeeNathees/pocketlang/blob/6d434db0cb7da2699c45b455f23032dab65b633b/src/pk_compiler.c#L2773)

------

> Right now ^C works anyway but in the future we might want more signals

Yeah you're right, it's too early to handle the signals, If we want something to exit the process properly it might be an `exit()` function. I'll add the future tag for this and let's not worry about it for now.

**Comment by ThakeeNathees** [comment]
Fixed by #138, but the signal handling is still in the future list.

**Comment by kseistrup** [comment]
> Fixed by #138

I'm sorry, but I just tested 794c789fcac23a3ac972c61e9ec58182d5a8a738 and I still see the same behaviour.

**Comment by ThakeeNathees** [comment]
@kseistrup Now, you can exit REPL properly with `exit()` function, ctrl+c will also terminate the process, but ctrl+d is not used for that purpose it'll pass the EOF character to the input and python REPL also seems like skips the ^D character. Yet the signal handling is still in the future list.

**Comment by kseistrup** [comment]
> ctrl+d is not used for that purpose it'll pass the EOF character to the input and python REPL also seems like skips the ^D character. 

The ^D will indeed pass the EOF character to the input, thus telling the REPL that this is the end of the road and that it should exit. And that is precisely what the Python REPL does: exit (at least on Linux, which is the only platform I have access to). I see no reason to involve signal handling in this.

On Linux, ^D is one of several possible normal ways of exiting a program that reads from standard input when standard input is a TTY.

**Comment by ThakeeNathees** [comment]
> On Linux, ^D is one of several possible normal ways of exiting a program that reads from standard input when standard input is a TTY.

I've just installed WSL/python on windows, and yeah, It does exit the terminal. Guess it's something platform-dependent, I'll take a look at this. @kseistrup

**Comment by kseistrup** [comment]
I believe the corresponding sequence is ^Z on Windows, but I'm not sure.

**Comment by ThakeeNathees** [comment]
> I believe the corresponding sequence is ^Z on Windows, but I'm not sure.

Yeah, ^Z send EOF to the terminal in windows, like ^D on POSIX.

----

*Edit:* A discussion about detecting Ctrl+D on stackoverflow https://stackoverflow.com/questions/35823864/detecting-ctrl-d-in-c (might be helpful)

**Comment by tsujp** [comment]
I narrowed it down to (I think) the line responsible for ^D (EOF) causing the `>>>` spam but I couldn't fix it (so maybe it wasn't the right line after all). I can have another crack at it now if you aren't already @ThakeeNathees but I make no promises.
